#!/usr/bin/env bash

KEYBOARD_MAP="fr"
POLYBAR_CONFIG="$HOME/.config/polybar/config"
POLYBAR_MONITOR="DP-2"

setxkbmap "$KEYBOARD_MAP" -option caps:escape

urxvtd --quiet --opendisplay --fork

[ -f "$HOME/.fehbg" ] && source "$HOME/.fehbg"

[ -f "$POLYBAR_CONFIG" ] && MONITOR="${POLYBAR_MONITOR}" polybar main
